# Generated by Django 5.0.1 on 2025-08-29 00:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_reservation_participants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="participants",
        ),
        migrations.AddField(
            model_name="reservation",
            name="applicant_names",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="lounge",
            name="number",
            field=models.IntegerField(choices=[(1, "1"), (2, "2")], unique=True),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                fields=("lounge", "start_time"), name="unique_lounge_timeslot"
            ),
        ),
    ]
